stages:
  - fetch_token
  - setup_ngrok

fetch_token:
  stage: fetch_token
  image: alpine:latest
  script:
    - apk add --no-cache git
    - git clone https://<username>:<access_token>@gitlab.com/<username>/<repository>.git
    - export NGR_AUTH_TOKEN=$(cat <repository>/ngrok_token.txt)
  artifacts:
    reports:
      dotenv: .env

setup_ngrok:
  stage: setup_ngrok
  image: ngrok/ngrok:latest
  script:
    - ./ngrok authtoken $NGR_AUTH_TOKEN
    - ./ngrok http 80
